MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/heshuting/.cache/torch/checkpoints/jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('2')
  TRANSFORMER_TYPE: 'deit_small_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  SIE_CAMERA: True
  SIE_VIEW: True
  ID_LOSS_WEIGHT: 1.0
  TRIPLET_LOSS_WEIGHT: 0.7 #logs1.2都是0.2 logs3是0.7, logs4是0.5, s5-0.5
  C_LOSS_WEIGHT: 0.7 #logs1.2.3都是0.5, logs4是0.6, s5-0.5
  XT_LOSS_WEIGHT: 0.5
  YT_LOSS_WEIGHT: 0.5
  ID_LOSS_TYPE: 'softmax'
  DIST_TRAIN: False
INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('shipreid')
  ROOT_DIR: ('./todataset')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 0

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 1000
  BASE_LR: 0.001 #0.008
  IMS_PER_BATCH: 64  #64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 100
  LOG_PERIOD: 30
  EVAL_PERIOD: 1000
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: 'logs/transformer_300.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './logs/'


